version: '3.8'

services:
  web:
    build: .
    ports:
      -3000:3000
    volumes:
      -.:usr/src/app
    command: air cmd/main.go -b 0.0.0.0

  db:
    image: postgres:alphine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_NAME=${DB_NAME}
    ports:
      -5432:5432
    volumes:
      -postgres-db:/var/lib/postgressql/data
volumes:
  postgres-db: